version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    networks:
      - my_network
    ports:
      - "27018:27017"
    
  redis:
    image: redis
    container_name: redis_container
    networks:
      - my_network
    ports:
      - "6379:6379"